create extension if not exists pgcrypto;

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  workplace_id text not null default 'default',
  email text not null,
  name text not null default '',
  picture text not null default '',
  created_at timestamptz not null default now(),
  unique (email, workplace_id)
);

create table if not exists public.chat_sessions (
  id uuid primary key,
  workplace_id text not null default 'default',
  user_id uuid not null references public.users(id) on delete cascade,
  title text not null default 'New Chat',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  workplace_id text not null default 'default',
  session_id uuid not null references public.chat_sessions(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.reminders (
  id bigint generated by default as identity primary key,
  workplace_id text not null default 'default',
  user_id uuid not null references public.users(id) on delete cascade,
  title text not null,
  time text not null,
  repeat text not null default 'Daily',
  notes text default '',
  icon text default '💊',
  color text default '#E6F1FB',
  done boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.health_records (
  id bigint generated by default as identity primary key,
  workplace_id text not null default 'default',
  user_id uuid not null references public.users(id) on delete cascade,
  type text not null,
  data text not null,
  notes text default '',
  recorded_at timestamptz not null default now()
);

create index if not exists idx_users_workplace_email
  on public.users (workplace_id, email);

create index if not exists idx_chat_sessions_owner
  on public.chat_sessions (workplace_id, user_id, updated_at desc);

create index if not exists idx_chat_messages_session
  on public.chat_messages (workplace_id, session_id, created_at);

create index if not exists idx_reminders_owner
  on public.reminders (workplace_id, user_id, created_at desc);

create index if not exists idx_health_records_owner
  on public.health_records (workplace_id, user_id, recorded_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_chat_sessions_updated_at on public.chat_sessions;
create trigger set_chat_sessions_updated_at
before update on public.chat_sessions
for each row
execute function public.set_updated_at();
